#!/usr/bin/env python3
"""
Gradio-based Web Interface for Amharic Automatic Speech Recognition.

This script launches a local web server where users can upload audio files
and receive Amharic transcripts generated by a fine-tuned Whisper model.
"""

import os
import sys
import gradio as gr

# Ensure the 'src' directory is in the Python path so we can import our package
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "src")
if SRC not in sys.path:
    sys.path.insert(0, SRC)

from amharic_asr.transcribe import transcribe_audio

def process_audio(audio_path, model_dir):
    """
    Wrapper function for the Gradio interface to handle inputs and errors.

    Args:
        audio_path: Path to the uploaded audio file (provided by Gradio).
        model_dir: Path to the directory where the model is stored.

    Returns:
        The generated transcript or an error message.
    """
    if not audio_path:
        return "Please upload an audio file."
    if not model_dir:
        return "Please provide a model directory."
    if not os.path.exists(model_dir):
        return f"Model directory not found: {model_dir}"

    try:
        # Call the core transcription logic from the src package
        transcript = transcribe_audio(model_dir, audio_path)
        return transcript
    except Exception as e:
        return f"Error during transcription: {str(e)}"

def main():
    """Defines and launches the Gradio web interface."""
    demo = gr.Interface(
        fn=process_audio,
        inputs=[
            gr.Audio(type="filepath", label="Upload Amharic Audio"),
            gr.Textbox(
                label="Model Directory",
                value="outputs/amharic-whisper-small-ft",
                placeholder="Path to fine-tuned model"
            )
        ],
        outputs=gr.Textbox(label="Transcript"),
        title="Amharic ASR Web Interface",
        description="Upload an Amharic audio file to generate its transcript using a fine-tuned Whisper model."
    )

    # Launch the server, accessible locally at http://0.0.0.0:7860
    demo.launch(server_name="0.0.0.0", server_port=7860)

if __name__ == "__main__":
    main()
